import type { ListingProject } from "./types";

export const LISTING_PROJECTS: ListingProject[] = [
  {
    id: "PRJ-101",
    name: "Brand refresh",
    client: "Acme Corp",
    status: "In progress",
    budget: "$48,000",
    dueDate: "2026-08-15",
    ownerName: "Priya Nair",
    ownerInitials: "PN",
  },
  {
    id: "PRJ-102",
    name: "Mobile app redesign",
    client: "Northwind Labs",
    status: "At risk",
    budget: "$76,500",
    dueDate: "2026-08-02",
    ownerName: "Daniel Cho",
    ownerInitials: "DC",
  },
  {
    id: "PRJ-103",
    name: "Design system rollout",
    client: "Vantage Health",
    status: "In progress",
    budget: "$112,000",
    dueDate: "2026-09-10",
    ownerName: "Meera Iyer",
    ownerInitials: "MI",
  },
  {
    id: "PRJ-104",
    name: "Marketing site rebuild",
    client: "Acme Corp",
    status: "Completed",
    budget: "$34,200",
    dueDate: "2026-06-30",
    ownerName: "Owen Bennett",
    ownerInitials: "OB",
  },
  {
    id: "PRJ-105",
    name: "AI copilot prototype",
    client: "Solace Robotics",
    status: "Planning",
    budget: "$95,000",
    dueDate: "2026-10-01",
    ownerName: "Priya Nair",
    ownerInitials: "PN",
  },
  {
    id: "PRJ-106",
    name: "Onboarding flow audit",
    client: "Northwind Labs",
    status: "Completed",
    budget: "$18,750",
    dueDate: "2026-05-20",
    ownerName: "Daniel Cho",
    ownerInitials: "DC",
  },
  {
    id: "PRJ-107",
    name: "Design ops playbook",
    client: "Vantage Health",
    status: "Cancelled",
    budget: "$26,000",
    dueDate: "2026-07-11",
    ownerName: "Meera Iyer",
    ownerInitials: "MI",
  },
  {
    id: "PRJ-108",
    name: "Investor deck refresh",
    client: "Solace Robotics",
    status: "In progress",
    budget: "$12,400",
    dueDate: "2026-08-22",
    ownerName: "Owen Bennett",
    ownerInitials: "OB",
  },
  {
    id: "PRJ-109",
    name: "Retail loyalty app",
    client: "Lumen Retail",
    status: "In progress",
    budget: "$54,000",
    dueDate: "2026-09-18",
    ownerName: "Priya Nair",
    ownerInitials: "PN",
  },
  {
    id: "PRJ-110",
    name: "Support portal revamp",
    client: "Vantage Health",
    status: "Planning",
    budget: "$41,000",
    dueDate: "2026-10-12",
    ownerName: "Owen Bennett",
    ownerInitials: "OB",
  },
];
