import type { ApiResponse, Project } from "@/types";

export const mockProjectsResponse: ApiResponse<Project[]> = {
  status: 200,
  message: "OK",
  data: [
    {
      id: "proj_1",
      name: "Aurora Care Portal",
      clientName: "Aurora Health",
      status: "in-review",
      ownerName: "Daniel Cho",
      ownerInitials: "DC",
      updatedAt: "2026-07-17T14:40:00Z",
    },
    {
      id: "proj_2",
      name: "Northwind Mobile App",
      clientName: "Northwind Traders",
      status: "in-progress",
      ownerName: "Priya Sharma",
      ownerInitials: "PS",
      updatedAt: "2026-07-18T09:15:00Z",
    },
    {
      id: "proj_3",
      name: "Lumen Storefront Refresh",
      clientName: "Lumen Retail",
      status: "completed",
      ownerName: "Owen Bennett",
      ownerInitials: "OB",
      updatedAt: "2026-07-12T16:05:00Z",
    },
    {
      id: "proj_4",
      name: "Vertex Ops Dashboard",
      clientName: "Vertex Robotics",
      status: "at-risk",
      ownerName: "Meera Iyer",
      ownerInitials: "MI",
      updatedAt: "2026-07-19T11:30:00Z",
    },
    {
      id: "proj_5",
      name: "Solace Onboarding Flow",
      clientName: "Solace Financial",
      status: "on-hold",
      ownerName: "Alicia Wong",
      ownerInitials: "AW",
      updatedAt: "2026-07-09T08:20:00Z",
    },
    {
      id: "proj_6",
      name: "Aurora Design System",
      clientName: "Aurora Health",
      status: "in-progress",
      ownerName: "Priya Sharma",
      ownerInitials: "PS",
      updatedAt: "2026-07-20T13:00:00Z",
    },
    {
      id: "proj_7",
      name: "Northwind Analytics",
      clientName: "Northwind Traders",
      status: "in-review",
      ownerName: "Daniel Cho",
      ownerInitials: "DC",
      updatedAt: "2026-07-15T10:45:00Z",
    },
    {
      id: "proj_8",
      name: "Lumen Loyalty Program",
      clientName: "Lumen Retail",
      status: "completed",
      ownerName: "Owen Bennett",
      ownerInitials: "OB",
      updatedAt: "2026-07-05T15:10:00Z",
    },
  ],
};
